# Generated by Django 5.1.4 on 2025-02-28 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.CharField(max_length=50)),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('communication_id', models.AutoField(primary_key=True, serialize=False)),
                ('primary_phone', models.CharField()),
                ('phone_verification_status', models.BooleanField(default=False)),
                ('secondary_phone', models.CharField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_verification_status', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=10, unique=True)),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=10, unique=True)),
                ('currency_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IndustrySegment',
            fields=[
                ('segment_id', models.AutoField(primary_key=True, serialize=False)),
                ('segment_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tax_identifier',
            fields=[
                ('tax_identifier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tax_demography', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile_app.city')),
                ('country_code', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile_app.country')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile_app.currency'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile_app.address')),
                ('communication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile_app.communication')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile_app.currency')),
                ('industry_segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile_app.industrysegment')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=50)),
                ('iso_code', models.CharField(max_length=10, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile_app.country')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile_app.state'),
        ),
        migrations.AddField(
            model_name='address',
            name='state_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile_app.state'),
        ),
        migrations.CreateModel(
            name='state_join_taxid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile_app.state')),
                ('tax_identifier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile_app.tax_identifier')),
            ],
        ),
        migrations.CreateModel(
            name='country_join_taxid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile_app.country')),
                ('tax_identifier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile_app.tax_identifier')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('user_profile_bio', models.TextField(blank=True, max_length=300)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile_app.address')),
                ('communication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile_app.communication')),
            ],
        ),
        migrations.AddField(
            model_name='tax_identifier',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_identifier_created', to='Profile_app.userprofile'),
        ),
        migrations.AddField(
            model_name='tax_identifier',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_identifier_updated', to='Profile_app.userprofile'),
        ),
        migrations.CreateModel(
            name='organization_join_taxid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile_app.organization')),
                ('tax_identifier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile_app.tax_identifier')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_taxid_created', to='Profile_app.userprofile')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_taxid_updated', to='Profile_app.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_created', to='Profile_app.userprofile'),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_updated', to='Profile_app.userprofile'),
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('consent_id', models.AutoField(primary_key=True, serialize=False)),
                ('consent_date', models.DateTimeField()),
                ('consent_type', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile_app.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='communication',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_created', to='Profile_app.userprofile'),
        ),
        migrations.AddField(
            model_name='communication',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_updated', to='Profile_app.userprofile'),
        ),
        migrations.AddField(
            model_name='address',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_created', to='Profile_app.userprofile'),
        ),
        migrations.AddField(
            model_name='address',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_updated', to='Profile_app.userprofile'),
        ),
    ]
