# Generated by Django 5.1.6 on 2025-03-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_app', '0002_alter_organization_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
