# Generated by Django 5.1.6 on 2025-03-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_app', '0003_alter_organization_organization_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_id',
        ),
    ]
