# Generated by Django 5.1.4 on 2025-03-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_app', '0004_remove_organization_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_by',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communication',
            name='created_by',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communication',
            name='updated_by',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
