# Generated by Django 5.1.3 on 2025-04-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_app', '0005_alter_address_created_by_alter_address_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization_join_taxid',
            name='created_by',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization_join_taxid',
            name='updated_by',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tax_identifier',
            name='created_by',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tax_identifier',
            name='updated_by',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
