# Generated by Django 5.1.3 on 2025-04-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_app', '0006_alter_organization_join_taxid_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='primary_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='communication',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
