# Generated by Django 5.1.3 on 2025-04-18 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_app', '0007_alter_communication_primary_phone_and_more'),
        ('Profile_app', '0008_auto_20250418_0415'),
    ]

    operations = [
    ]
