# Generated by Django 5.1.3 on 2025-04-29 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_app', '0008_add_indian_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
            ],
        ),
    ]
