# Generated by Django 5.1.3 on 2025-04-23 10:39

from django.db import migrations

def add_indian_states(apps, schema_editor):
    State = apps.get_model('Profile_app', 'State')
    Country = apps.get_model('Profile_app', 'Country')

    try:
        india = Country.objects.get(id=1)  # Or use country_name="INDIA" if safer
    except Country.DoesNotExist:
        return  # Skip if country doesn't exist

    state_data = [
    {
        "id": 1,
        "state_name": "Andhra Pradesh",
        "state_code": "AP",
        "iso_code": "IN-AP",
        "country": 1
    },
    {
        "id": 2,
        "state_name": "Arunachal Pradesh",
        "state_code": "AR",
        "iso_code": "IN-AR",
        "country": 1
    },
    {
        "id": 3,
        "state_name": "Assam",
        "state_code": "AS",
        "iso_code": "IN-AS",
        "country": 1
    },
    {
        "id": 4,
        "state_name": "Bihar",
        "state_code": "BR",
        "iso_code": "IN-BR",
        "country": 1
    },
    {
        "id": 5,
        "state_name": "Chhattisgarh",
        "state_code": "CT",
        "iso_code": "IN-CT",
        "country": 1
    },
    {
        "id": 6,
        "state_name": "Goa",
        "state_code": "GA",
        "iso_code": "IN-GA",
        "country": 1
    },
    {
        "id": 7,
        "state_name": "Gujarat",
        "state_code": "GJ",
        "iso_code": "IN-GJ",
        "country": 1
    },
    {
        "id": 8,
        "state_name": "Haryana",
        "state_code": "HR",
        "iso_code": "IN-HR",
        "country": 1
    },
    {
        "id": 9,
        "state_name": "Himachal Pradesh",
        "state_code": "HP",
        "iso_code": "IN-HP",
        "country": 1
    },
    {
        "id": 10,
        "state_name": "Jharkhand",
        "state_code": "JH",
        "iso_code": "IN-JH",
        "country": 1
    },
    {
        "id": 11,
        "state_name": "Karnataka",
        "state_code": "KA",
        "iso_code": "IN-KA",
        "country": 1
    },
    {
        "id": 12,
        "state_name": "Kerala",
        "state_code": "KL",
        "iso_code": "IN-KL",
        "country": 1
    },
    {
        "id": 13,
        "state_name": "Madhya Pradesh",
        "state_code": "MP",
        "iso_code": "IN-MP",
        "country": 1
    },
    {
        "id": 14,
        "state_name": "Maharashtra",
        "state_code": "MH",
        "iso_code": "IN-MH",
        "country": 1
    },
    {
        "id": 15,
        "state_name": "Manipur",
        "state_code": "MN",
        "iso_code": "IN-MN",
        "country": 1
    },
    {
        "id": 16,
        "state_name": "Meghalaya",
        "state_code": "ML",
        "iso_code": "IN-ML",
        "country": 1
    },
    {
        "id": 17,
        "state_name": "Mizoram",
        "state_code": "MZ",
        "iso_code": "IN-MZ",
        "country": 1
    },
    {
        "id": 18,
        "state_name": "Nagaland",
        "state_code": "NL",
        "iso_code": "IN-NL",
        "country": 1
    },
    {
        "id": 19,
        "state_name": "Odisha",
        "state_code": "OR",
        "iso_code": "IN-OR",
        "country": 1
    },
    {
        "id": 20,
        "state_name": "Punjab",
        "state_code": "PB",
        "iso_code": "IN-PB",
        "country": 1
    },
    {
        "id": 21,
        "state_name": "Rajasthan",
        "state_code": "RJ",
        "iso_code": "IN-RJ",
        "country": 1
    },
    {
        "id": 22,
        "state_name": "Sikkim",
        "state_code": "SK",
        "iso_code": "IN-SK",
        "country": 1
    },
    {
        "id": 23,
        "state_name": "Tamil Nadu",
        "state_code": "TN",
        "iso_code": "IN-TN",
        "country": 1
    },
    {
        "id": 24,
        "state_name": "Telangana",
        "state_code": "TG",
        "iso_code": "IN-TG",
        "country": 1
    },
    {
        "id": 25,
        "state_name": "Tripura",
        "state_code": "TR",
        "iso_code": "IN-TR",
        "country": 1
    },
    {
        "id": 26,
        "state_name": "Uttarakhand",
        "state_code": "UT",
        "iso_code": "IN-UT",
        "country": 1
    },
    {
        "id": 27,
        "state_name": "Uttar Pradesh",
        "state_code": "UP",
        "iso_code": "IN-UP",
        "country": 1
    },
    {
        "id": 28,
        "state_name": "West Bengal",
        "state_code": "WB",
        "iso_code": "IN-WB",
        "country": 1
    }
]

    for state in state_data:
        State.objects.update_or_create(
            iso_code=state["iso_code"],
            defaults={
                "state_name": state["state_name"],
                "state_code": state["state_code"],
                "country": india
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('Profile_app', '0009_merge_20250418_0438'),
    ]

    operations = [
        migrations.RunPython(add_indian_states),
    ]
