# Generated by Django 5.1.3 on 2025-05-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_app', '0009_userprofile_cover_image_paymentmethods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
