# Generated by Django 5.1.3 on 2025-05-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_app', '0010_alter_userprofile_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
