# Generated by Django 5.1.3 on 2025-05-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_app', '0011_alter_communication_primary_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
